### ISSUE TITLE
Why the filesize is larger than JSARToolKit5?

### ISSUE THREAD

**Issue by shrekuu** [webarkit/jsartoolkitNFT#88]
![image](https://user-images.githubusercontent.com/3136026/107174417-1b47c080-6a05-11eb-81f0-72bd08fd1878.png)

I think with only NFT feature, it should be smaller.  😅   I am trying to implement this in Wechat Miniprogram. The package size cannot exceed 2MB. 🤣 ARnft is almost 2MB.

**Comment by kalwalt** [comment]
it depends what do you compare. if you make comparison between the Emscripten build files [artoolkit.min.js ](https://github.com/kalwalt/jsartoolkit5/blob/master/build/artoolkit.min.js) and [artoolkitNFT.min.js](https://github.com/webarkit/jsartoolkitNFT/blob/master/build/artoolkitNFT.min.js) this last will be smaller (300 kb smaller) but if you compare [artoolkitNFT.min.js](https://github.com/webarkit/jsartoolkitNFT/blob/master/build/artoolkitNFT.min.js) with the dist file  [ARToolKitNFT.js](https://github.com/webarkit/jsartoolkitNFT/blob/master/dist/ARToolkitNFT.js) this last will be bigger than the build file because has the ES6 support. As a  consquence ARnft can not be smaller at all because depends on this last. One reason is that embedd the inlined worker and it has also Threejs rendering features bundled. We are trying to move these last outside in a separate repository and add typescript definitions. I hope that this clarify things a bit.

**Comment by shrekuu** [comment]
@kalwalt Thanks for the explanation. :D
